### ISSUE TITLE
Connect to stream.wikimedia.org via HTTPS

### ISSUE THREAD

**Issue by atdt** [mitar/mediawiki-stream#1]
Hello, could you update your code to connect to stream.wikimedia.org via HTTPS? HTTP access is deprecated and will be shut off eventually.  I think it would be as simple as changing 'http:' to 'https:' in https://github.com/mitar/mediawiki-stream/blob/master/server/stream.coffee#L54 .

**Comment by mitar** [comment]
Sure. :-)

Do I also have to update the socket-io-client library? Last time I had to downgrade it to 0.9.17 because Wikimedia's side did not work with latest version.

**Comment by mitar** [comment]
Done with 02b9ab1ebd1392eff7cd7b13724fa2ce128805ca.
