### ISSUE TITLE
Migrate from socket.io to SSE / EventSource based EventStreams

### ISSUE THREAD

**Issue by ottomata** [mitar/mediawiki-stream#2]
Hiya!  More protocol changes from us here over at WMF.  We're planning on decomissioning the socket.io based RCStream in July this year.  We've built a new service called EventStreams that takes its place.  

- https://blog.wikimedia.org/2017/03/20/eventstreams/
- https://wikitech.wikimedia.org/wiki/EventStreams

From looking at stream.coffee, it looks like switching should be pretty easy.  Let me know if  I can help.  Thanks!

**Comment by mitar** [comment]
Interesting. How can I limit which events I am getting? Before I could limit only to a particular wiki, or just to bots, or just minor changes.

**Comment by mitar** [comment]
Migrated. Now we use event streams. :-)

Check it out: https://wikimedia.meteorapp.com/

Do you know if there is any place where I could list this so that other developers interested in the streaming API to Wikipedia could find it?

**Comment by mitar** [comment]
BTW, how did @atdt  and you found this to report changes in streaming API? I think this is great help! :-)

**Comment by ottomata** [comment]
> Interesting. How can I limit which events I am getting? Before I could limit only to a particular wiki, or just to bots, or just minor changes.

Yeah, this is a feature we haven't yet added.  We weren't totally sure how useful it actually is, and it is a little complicated to implement.  If you need it, or find it really useful, can you chime in over at the [EventStreams Talk page](https://www.mediawiki.org/wiki/Topic:Tkjkabtyakpm967t)?

> Do you know if there is any place where I could list this so that other developers interested in the streaming API to Wikipedia could find it?

I've started a [Powered By](https://wikitech.wikimedia.org/wiki/EventStreams/Powered_By) page on wikitech, please edit and add your tool there!  I'm not sure if there are better places at this time.

> how did @atdt and you found this to report changes in streaming API

I don't know about @atdt, but I found it by searching github for 'stream.wikimedia.org' :)

> Migrated. Now we use event streams. :-)

Awesooome!

**Comment by mitar** [comment]
> Yeah, this is a feature we haven't yet added. We weren't totally sure how useful it actually is, and it is a little complicated to implement.

In fact I do not really need it. I am consuming all events anyway. And then allow users to limit it using MongoDB queries. So in my particular case the API works perfectly.

> I've started a Powered By page on wikitech, please edit and add your tool there! I'm not sure if there are better places at this time.

Aha. In my case it is more a tool for developers, not really an end-user app. But I can add it.

**Comment by mitar** [comment]
> Migrated. Now we use event streams. :-)

I did notice one downside. That is probably the issue of the EventStreams package. That if the TCP connection breaks (like if I move to another WiFi while running local development version of this app), no error is really thrown to the app using EventStreams, it just stops delivering messages.

**Comment by ottomata** [comment]
> Aha. In my case it is more a tool for developers, not really an end-user app. But I can add it.

Yeah add it!  Tools and end user apps are welcome.

>  That if the TCP connection breaks (like if I move to another WiFi while running local development version of this app), no error is really thrown to the app using EventStreams, it just stops delivering messages.

Hm, that's not supposed to happen.  It might not throw an error, but it should retry connecting and eventually re-send with the `Last-Event-ID` header set to where it last left off.

**Comment by ottomata** [comment]
I just tried with nodejs eventsource, and it worked!

```
var EventSource = require('eventsource');
var url = 'https://stream.wikimedia.org/v2/stream/recentchange';

console.log(`Connecting to EventStreams at ${url}`);
var eventSource = new EventSource(url);
eventSource.onmessage = function(event) {
    // event.data will be a JSON string containing the message event.
    var change = JSON.parse(event.data)
    console.log(`at ${change.meta.offset}, last event id is ${event.lastEventId}`);
};
```

I let this run, disconnected my wifi, then reconnected, and eventually I started getting events again from exactly where I had left off.

**Comment by mitar** [comment]
> and eventually

How long have you been waiting?

**Comment by ottomata** [comment]
It took maybe around a minute.

**Comment by mitar** [comment]
OK, I definitely waited for longer than that. Anyway, I do not think it is critical. This was happening only in development anyway.
