### ISSUE TITLE
Locking scrolling does not work in Chrome, but it does in Firefox

### ISSUE THREAD

**Issue by mitar** [mitar/mediawiki-stream#3]
Web interface to the stream should work so that when you scroll to results, a particular result stays shown even as more results are added above. This does not really work in Chrome, but it does in Firefox.

**Comment by mitar** [comment]
StackOverflow question: https://stackoverflow.com/questions/42947024/keeping-scroll-position-when-adding-elements-on-top-works-in-firefox-but-not-chr

**Comment by theodorDiaconu** [comment]
@mitar this is usually a hard problem to solve. The solutions we apply in social networks, is that no new items are inserted unless you are on a certain scroll position. And if new items are detected you get like a floating bubble on top saying "new results" and on click takes you back to scrollY: 0, and it can resume loading.

**Comment by mitar** [comment]
But it works in Firefox so well. :-(

**Comment by mitar** [comment]
It seems it works now.
